// ─────────────────────────────────────────────────────────────────────────────
// Centralized Mock Data — single source of truth for all demo/placeholder data.
//
// Saudi-localized dataset generated by mocks/saudiMockData.js
// for board presentations and demo dashboards.
// ─────────────────────────────────────────────────────────────────────────────

import {
  ngoProfiles,
  userDirectory,
  topMarketersLeaderboard,
  aggregateWeeklyTrend,
  totalActiveLinks,
  totalCollectedFunds,
  generateBeneficiaryDigest,
} from "@/mocks/saudiMockData";

// ── NGOs (3 prominent Saudi NGOs) ───────────────────────────────────────────
export const mockNgos = ngoProfiles.map(n => ({
  ngo_id: n.id,
  ngo_name: n.name,
  city: n.city,
  total_cases: n.beneficiary_target,
  activity_pct: n.status === "active"
    ? n.id === "NGO-RUH-001" ? 92 : 78
    : 12,
  status: n.status,
  category: n.category,
  responsible_person: n.responsible_person,
  donation_url: n.donation_url,
}));

// ── Beneficiaries (20 recent cases from the generator) ──────────────────────
export const mockBeneficiaries = generateBeneficiaryDigest(20).map((b, i) => ({
  beneficiary_id: b.beneficiary_id,
  full_name: b.full_name,
  case_type: b.case_type,
  city: b.city,
  priority: b.priority,
  researcher_name: b.researcher_name,
  created_at: new Date(2025, 5, 20 - i).toLocaleDateString("ar-SA", { day: "numeric", month: "short", year: "numeric" }),
}));

// ── Researchers ──────────────────────────────────────────────────────────────
export const mockResearchers = userDirectory
  .filter(u => u.role === "researcher")
  .map((u, i) => ({
    researcher_id: u.id,
    full_name: u.full_name,
    city: u.city,
    ngo_name: u.ngo_name,
    completed_cases: 42 - i * 11,
    status: "active",
  }));

// ── Marketers ────────────────────────────────────────────────────────────────
export const mockMarketers = userDirectory
  .filter(u => u.role === "marketer")
  .map(u => ({
    marketer_id: u.id,
    full_name: u.full_name,
    ngo_name: u.ngo_name,
    campaigns_count: Math.floor(Math.random() * 8) + 8,
    status: "active",
  }));

// ── Audit Logs (activity feed) ───────────────────────────────────────────────
export const mockAuditLogs = [
  { log_id: 1, log_text: "إضافة منظمة جديدة: جمعية الإحسان",            created_at: "منذ ٢ دقيقة",  log_type: "ngo" },
  { log_id: 2, log_text: "باحث: سارة المطيري أضافت ٣ حالات جديدة",      created_at: "منذ ٨ دقائق",  log_type: "researcher" },
  { log_id: 3, log_text: "انطلاق حملة 'رمضان الخيري' بنجاح",            created_at: "منذ ٢٠ دقيقة", log_type: "campaign" },
  { log_id: 4, log_text: "تسجيل ١٢ مستفيداً جديداً هذا اليوم",          created_at: "منذ ٣٥ دقيقة", log_type: "beneficiary" },
  { log_id: 5, log_text: "مراجعة طلب تسجيل: مؤسسة الأمل",               created_at: "منذ ساعة",     log_type: "ngo" },
  { log_id: 6, log_text: "أحمد العتيبي أتم ٩ حالات هذا الأسبوع",        created_at: "منذ ساعتين",   log_type: "researcher" },
];

export const mockLiveAuditEvents = [
  { log_id: 7, log_text: "انضمام مسوّق جديد: خالد الحربي",              log_type: "campaign" },
  { log_id: 8, log_text: "تحديث بيانات منظمة: مركز رعاية الطفل",        log_type: "ngo" },
  { log_id: 9, log_text: "نوف الزهراني: تسجيل حالتين ميدانيتين",        log_type: "researcher" },
];

// ── Chart Series ─────────────────────────────────────────────────────────────
export const mockGrowthSeries = [
  { month: "يناير",  مستفيدون: 180, منظمات: 38, باحثون: 18 },
  { month: "فبراير", مستفيدون: 220, منظمات: 40, باحثون: 19 },
  { month: "مارس",   مستفيدون: 260, منظمات: 41, باحثون: 21 },
  { month: "أبريل",  مستفيدون: 295, منظمات: 43, باحثون: 22 },
  { month: "مايو",   مستفيدون: 340, منظمات: 45, باحثون: 23 },
  { month: "يونيو",  مستفيدون: 390, منظمات: 48, باحثون: 26 },
  { month: "يوليو",  مستفيدون: 426, منظمات: 50, باحثون: 28 },
  { month: "أغسطس",  مستفيدون: 471, منظمات: 52, باحثون: 30 },
  { month: "سبتمبر", مستفيدون: 510, منظمات: 55, باحثون: 32 },
  { month: "أكتوبر", مستفيدون: 548, منظمات: 57, باحثون: 34 },
  { month: "نوفمبر", مستفيدون: 580, منظمات: 59, باحثون: 35 },
  { month: "ديسمبر", مستفيدون: 626, منظمات: 61, باحثون: 38 },
];

export const mockPrioritySeries = [
  { month: "يناير",  عاجل: 22, مرتفع: 45, متوسط: 110, منخفض: 60 },
  { month: "فبراير", عاجل: 28, مرتفع: 52, متوسط: 98,  منخفض: 55 },
  { month: "مارس",   عاجل: 19, مرتفع: 48, متوسط: 125, منخفض: 70 },
  { month: "أبريل",  عاجل: 35, مرتفع: 60, متوسط: 140, منخفض: 65 },
  { month: "مايو",   عاجل: 30, مرتفع: 55, متوسط: 132, منخفض: 72 },
  { month: "يونيو",  عاجل: 47, مرتفع: 63, متوسط: 155, منخفض: 80 },
];

export const mockStatusDistribution = [
  { name: "حالات نشطة",   value: 312, color: "#0c3140" },
  { name: "حالات مدعومة", value: 178, color: "#00A651" },
  { name: "حالات عاجلة",  value: 47,  color: "#dc2626" },
  { name: "مؤرشفة",       value: 89,  color: "#94a3b8" },
];